# Generated by Django 5.1.5 on 2025-01-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personName', models.CharField(max_length=127)),
                ('personEmail', models.CharField(max_length=127)),
                ('personComment', models.CharField(max_length=1023)),
            ],
        ),
    ]
